# Generated by Django 4.2.7 on 2023-12-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_archive', '0002_newsarchive_source_newsarchive_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarchive',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='newsarchive',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
    ]
