# Generated by Django 4.2.7 on 2023-12-04 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_archive', '0003_alter_newsarchive_content_alter_newsarchive_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarchive',
            name='source',
        ),
    ]
